INSERT INTO public.health_facilities (name, facility_type, region, town, address, phone, hours, services, is_public, notes) VALUES
('Mbabane Government Hospital','hospital','Hhohho','Mbabane','St Michaels Road, Mbabane','+268 2404 2431','24/7 emergency; clinics Mon-Fri 08:00-16:00',ARRAY['emergency','trauma','oncology','dental','eye care','maternity','paediatrics','NCD clinic','mental health unit'],true,'National referral hospital'),
('Raleigh Fitkin Memorial Hospital (RFM)','hospital','Manzini','Manzini','Ngwane Street, Manzini','+268 2505 2211','24/7 emergency',ARRAY['emergency','maternity','paediatrics','burns unit','HIV/ART','dental','one-stop GBV centre'],true,'Main mission referral hospital (Nazarene)'),
('Good Shepherd Hospital','hospital','Lubombo','Siteki','Siteki town','+268 2343 4133','24/7 emergency',ARRAY['TB treatment','eye unit','HIV/ART','general medicine','maternity'],true,'National TB referral hospital'),
('Hlathikhulu Government Hospital','hospital','Shiselweni','Hlathikhulu','Hlathikhulu','+268 2217 6111','24/7 emergency',ARRAY['emergency','maternity','HIV/ART','general medicine'],true,'Shiselweni regional hospital'),
('Pigg''s Peak Government Hospital','hospital','Hhohho','Pigg''s Peak','Pigg''s Peak','+268 2437 1111','24/7 emergency',ARRAY['emergency','maternity','HIV/ART','general medicine'],true,'Northern Hhohho regional hospital'),
('National Psychiatric Referral Hospital','hospital','Manzini','Manzini','Manzini','+268 2505 2262','Mon-Fri 08:00-16:00; in-patient 24/7',ARRAY['mental health','substance abuse','psychiatry','counselling'],true,'National mental health referral facility'),
('Mankayane Government Hospital','hospital','Manzini','Mankayane','Mankayane','+268 2538 8311','24/7 emergency',ARRAY['emergency','maternity','HIV/ART'],true,NULL),
('Nhlangano Health Centre','clinic','Shiselweni','Nhlangano','Nhlangano','+268 2207 8311','Mon-Sun 08:00-20:00',ARRAY['primary care','HIV/ART','TB','family planning'],true,NULL),
('Sithobela Health Centre','clinic','Lubombo','Sithobela','Sithobela','+268 2313 8000','Mon-Fri 08:00-16:00',ARRAY['primary care','HIV/ART','maternal health'],true,NULL),
('Dvokolwako Health Centre','clinic','Hhohho','Dvokolwako','Dvokolwako','+268 2384 4000','Mon-Fri 08:00-16:00',ARRAY['primary care','HIV/ART','maternity'],true,NULL),
('The Luke Commission (Miracle Campus)','mission','Manzini','Sidvokodvo','Miracle Campus, Sidvokodvo, Eswatini','+268 7606 8000','Mon-Fri 07:00-17:00',ARRAY['free surgery','HIV/ART','VMMC','eye care','dental','maternity','outreach','diagnostics'],true,'Free comprehensive care, no patient is turned away; email info@lukecommission.org'),
('Baylor Children''s Clinical Centre of Excellence','clinic','Hhohho','Mbabane','Mbabane Government Hospital grounds','+268 2404 9700','Mon-Fri 08:00-16:30',ARRAY['paediatric HIV/ART','youth-friendly services','child nutrition'],true,NULL),
('Family Life Association of Eswatini (FLAS) Mbabane','clinic','Hhohho','Mbabane','Mbabane','+268 2404 0665','Mon-Fri 08:00-17:00',ARRAY['HIV testing','PrEP','family planning','STI treatment','cervical cancer screening','VMMC'],false,'Also branches in Manzini, Nhlangano and Siteki'),
('Mbabane Clinic','private','Hhohho','Mbabane','St Michaels Road, Mbabane','+268 2404 2423','24/7',ARRAY['emergency','trauma','cardiology','surgery','maternity','general practice'],false,'Leading private hospital'),
('Manzini Clinic','private','Manzini','Manzini','Manzini','+268 2505 8000','24/7',ARRAY['emergency','general practice','maternity'],false,NULL),
('Swazi Med / MRI Emergency Services','private','Manzini','Matsapha','Matsapha','+268 2518 4000','24/7',ARRAY['ambulance','medical aid','emergency evacuation'],false,'Private ambulance and medical scheme'),
('Emergency Ambulance Service (National)','emergency','National','Nationwide',NULL,'977','24/7',ARRAY['ambulance','emergency response','trauma'],true,'Dial 977 anywhere in Eswatini'),
('Childline Eswatini / GBV Helpline','organisation','National','Nationwide',NULL,'116','24/7',ARRAY['child protection','GBV support','counselling'],true,'Toll-free'),
('SWAGAA (Swaziland Action Group Against Abuse)','organisation','Manzini','Manzini','Manzini HQ','+268 2505 4532','Mon-Fri 08:00-17:00; crisis line 24/7',ARRAY['GBV counselling','legal support','shelter referral'],false,'Regional offices countrywide'),
('Ministry of Health Headquarters','organisation','Hhohho','Mbabane','Mhlambanyatsi Road, Mbabane','+268 2404 5628','Mon-Fri 08:00-16:45',ARRAY['policy','facility directory','programmes'],true,'gov.sz'),
('NERCHA','organisation','Hhohho','Mbabane','Mbabane','+268 2404 1703','Mon-Fri 08:00-16:30',ARRAY['HIV/AIDS coordination','partner directory'],true,'nercha.org.sz'),
('Cancer Association of Eswatini','organisation','Hhohho','Mbabane','Mbabane','+268 2404 3439','Mon-Fri 08:00-16:00',ARRAY['cancer screening','patient support','awareness'],false,NULL),
('Doctors Without Borders (MSF) Shiselweni','organisation','Shiselweni','Nhlangano','Nhlangano','+268 2207 8300','Mon-Fri 08:00-16:00',ARRAY['HIV/ART','drug-resistant TB','community outreach'],true,'Also Matsapha TB clinic'),
('Central Medical Stores','organisation','Manzini','Matsapha','Matsapha','+268 2518 6000','Mon-Fri 08:00-16:00',ARRAY['medicine supply','pharmacy'],true,'Public medicine distribution'),
('Eswatini Diabetes Association','organisation','Hhohho','Mbabane','Mbabane',NULL,'Mon-Fri 08:00-16:00',ARRAY['diabetes education','screening','support groups'],false,NULL),
('Lifeline Eswatini','organisation','Hhohho','Mbabane','Mbabane','+268 2404 2761','Mon-Fri 08:00-17:00',ARRAY['counselling','crisis support','mental health'],false,NULL);

INSERT INTO public.stock_listings (ticker, company_name, sector, market, currency, notes) VALUES
('FNBE','FNB Eswatini','Banking & Financial Services','Eswatini Stock Exchange','SZL','Tradeable via C-Trade'),
('NED','Nedbank Eswatini','Banking & Financial Services','Eswatini Stock Exchange','SZL','Tradeable via C-Trade'),
('SBC','Standard Bank Eswatini','Banking & Financial Services','Eswatini Stock Exchange','SZL',NULL),
('SEL','Swaziland Empowerment Limited','Investment','Eswatini Stock Exchange','SZL',NULL),
('SWP','Swazispa Holdings','Tourism & Leisure','Eswatini Stock Exchange','SZL',NULL),
('GRYS','Greystone Partners','Investment & Advisory','Eswatini Stock Exchange','SZL',NULL),
('INALA','Inala Capital','Investment','Eswatini Stock Exchange','SZL',NULL),
('NPC','Nedbank Preference Capital','Financial Instruments','Eswatini Stock Exchange','SZL',NULL),
('RSC','Royal Swaziland Sugar Corporation','Agriculture & Sugar','Eswatini Stock Exchange','SZL',NULL),
('AGS','Africa Grand Securities','Financial Services','Eswatini Stock Exchange','SZL',NULL);